---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgarding system packages
  apt:
    upgrade: dist

- name: Installing packages
  become: yes
  apt:
    pkg: "{{ item }}"
  with_items: 
   - unzip
   - tree
   - python-markdown
   - python-testresources
  state: present

- name: Creating group "demo"
  group:
    name: "{{ groupname }}"
  become: true

- name: Add user "demo"
  user:
    name: "{{ username }}"
    groups: "{{ groupname }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    append: yes
    state: present
    createhome: yes
  become: true

- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: "{{ pip_download_dir }}"
  owner: "{{ username }}"
  groups: "{{ groupname }}"

- name: Installing pip
  command: "python {{ pip_download_dir }}/get-pip.py"
  become: yes

- name: Installing pipenv
  become: yes
  command: pip install pipenv
