# UPGRADE PACKAGES AND INSTALL JAVA-1.8 + CONSUL + NOMAD + PIP

- hosts: server
  become: yes
  roles:
    - common
    - consul
    - nomad

###############################

# INSTALL JAVA-1.8 and ES-5.6.8
#- hosts: server
#  gather_facts: true
#  become: yes
#  vars:
#    java_home: /usr/lib/jvm/java-8-oracle/jre
#  roles:
#    - elasticsearch
